name: WeirdPicks
author: Wilobate
version: '1.1.3'
main: com.wilobate.weirdPicks.WeirdPicks
depend: 
- WorldGuard
- WorldEdit
commands:
  wpick:
    description: Summons mighty weapons.
    permission: wpick.explode
permissions:
  wpick.explode:
    description: Allows permission to use explosive pickaxes.
    default: true
  wpick.epick:
    description: Allows permission to give explosive pickaxes.
    default: op